name:                stack-tpls
version:             2.0.0
homepage:            https://github.com/matsubara0507/stack-tpls#readme
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          t12307043@gunma-u.ac.jp
copyright:           MATSUBARA Nobutada
category:            Web
description:         Please see the README on GitHub at <https://github.com/matsubara0507/stack-tpls#readme>

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude

- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiWayIf
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- RankNTypes
- StandaloneDeriving
- TypeFamilies
- TypeSynonymInstances
- TypeOperators

dependencies:
- aeson
- base >= 4.7 && < 5
- rio >= 0.1.1.0
- extensible >= 0.6
- mix
- morpheus-graphql-client
- req

library:
  source-dirs: src

executables:
  stack-tpls:
    main: Main.hs
    source-dirs: app
    dependencies:
    - stack-tpls
    - dotenv
    - githash
