resolver: lts-17.1
packages:
- .
extra-deps:
- extensible-0.8.1
- membership-0
- incremental-0.3.1
- github: matsubara0507/mix.hs
  commit: 75714be080db16f6a4f9d0a22e86947ffcdadc57
  subdirs:
  - mix
