resolver: lts-19.5
packages:
- .
extra-deps:
- extensible-0.8.3
- membership-0.0.1
- incremental-0.3.1
- github: matsubara0507/mix.hs
  commit: 9bcd386526fe10a025a23e951c2de86b05129b17
  subdirs:
  - mix
- morpheus-graphql-client-0.19.3
- morpheus-graphql-code-gen-0.19.3
- morpheus-graphql-core-0.19.3
