resolver: lts-15.0
packages:
- .
extra-deps:
- dotenv-0.8.0.4
- megaparsec-8.0.0
- extensible-0.7.1
- membership-0
- github: matsubara0507/mix.hs
  commit: 4978a33dec736799b30c14e215f7fa0f29fa2884
  subdirs:
  - mix
