name: Verify

on:
  pull_request: null
  push:
    branches:
    - master

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019]

    steps:
    - uses: actions/checkout@v2

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v1.1.2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/package.yaml') }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack-
    - uses: mstksg/setup-stack@v2

    - name: Install dependencies
      run: stack build --only-dependencies

    - name: Build application
      run: stack build

    - name: Exec application
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        stack exec -- stack-tpls --help
        stack exec -- stack-tpls --list
        stack exec -- stack-tpls github:matsubara0507/mix-cli.hsfiles
